export const keyboard = [
	[
		{ key: "q", result: "" },
		{ key: "w", result: "" },
		{ key: "e", result: "" },
		{ key: "r", result: "" },
		{ key: "t", result: "" },
		{ key: "y", result: "" },
		{ key: "u", result: "" },
		{ key: "i", result: "" },
		{ key: "o", result: "" },
		{ key: "p", result: "" },
	],
	[
		{ key: "a", result: "" },
		{ key: "s", result: "" },
		{ key: "d", result: "" },
		{ key: "f", result: "" },
		{ key: "g", result: "" },
		{ key: "h", result: "" },
		{ key: "j", result: "" },
		{ key: "k", result: "" },
		{ key: "l", result: "" },
	],
	[
		{ key: "enter" },
		{ key: "z", result: "" },
		{ key: "x", result: "" },
		{ key: "c", result: "" },
		{ key: "v", result: "" },
		{ key: "b", result: "" },
		{ key: "n", result: "" },
		{ key: "m", result: "" },

		{ key: "⌫" },
	],
];
